// 共享类型
export interface Usage {
  promptTokens?: number
  completionTokens?: number
  totalTokens?: number
  calls?: number
  /** 按模型累计 tokens（model -> tokens） */
  modelTokens?: Record<string, number>
}

export interface Member {
  memberId: string
  machineName: string
  ip: string
  isLocal?: boolean
  gatewayId?: string
  banned?: boolean
  displayName: string
  online: boolean
  joinedAt: number
  lastSeen: number
  usage?: Usage
}

export type View = 'members' | 'usage' | 'controls' | 'models' | 'connect' | 'details'

export interface BackendRow {
  id: string
  provider: string
  /** 标准模型列表（参考 cc-switch：一提供方多模型） */
  models: string[]
  baseUrl: string
  keySource: 'file' | 'env' | 'none'
  maskedKey: string
  registered: boolean
  /** 连接测试状态（DeepSeek Harness 式状态点：ok=绿 / fail=红 / untested=灰） */
  testStatus?: { status: 'ok' | 'fail' | 'untested'; latencyMs?: number; error?: string }
  /** 执行体种类（pair-integration P1）：pair / agent / none */
  executorKind?: 'pair' | 'agent' | 'none'
  /** 健康轮询状态（P1 四态状态点：ok=绿 / degraded=黄 / removed=红 / untested=灰） */
  healthState?: 'ok' | 'degraded' | 'removed' | 'untested'
  /** 健康轮询最近一次失败原因（悬停详情） */
  healthError?: string | null
  /** 健康轮询最近一次成功延迟（ms） */
  healthLatencyMs?: number | null
  /** 连续失败次数 */
  healthFailures?: number
  /** 轮询间隔（秒；默认 15） */
  pollIntervalSecs?: number
  /** C2C 分成比例预留字段（P2：provider_registry，仅落盘不参与逻辑） */
  splitRatio?: number | null
  /** 算力市场挂牌 ID 预留字段（P2：provider_registry，仅落盘不参与逻辑） */
  listingId?: string | null
}

// 中英双语字典（对应 DSH locale 模式）
export const L = {
  zh: {
    appName: 'AIPowerLink 管理面板',
    navMembers: '使用者',
    navUsage: '用量',
    navControls: '控制',
    navConnect: '接入',
    sharingOn: '共享中',
    sharingOff: '已暂停',
    startSharing: '开启共享',
    pauseSharing: '暂停共享',
    memberList: '使用者列表',
    memberLocal: '本机',
    machineName: '机器名',
    displayName: '显示名',
    ip: 'IP',
    status: '状态',
    online: '在线',
    offline: '离线',
    usage: '用量',
    totalTokens: '总 token',
    calls: '调用次数',
    usageTable: '用量统计',
    controls: '管理操作',
    kick: '拉黑',
    unban: '解禁',
    banned: '已拉黑',
    gateway: '网关 ID',
    details: '使用者详情',
    joinedAt: '接入时间',
    lastSeen: '最后活跃',
    back: '返回',
    noSelection: '选中使用者查看详情',
    refresh: '刷新',
    actions: '操作',
    exportCsv: '导出账单 CSV',
    quota: '配额',
    unlimited: '不限',
    models: '模型分布',
    navModels: '模型',
    modelsTitle: '模型设置',
    modelsHint: '填入各提供方的 API 密钥即可使用其模型',
    provider: '提供方',
    providerCustom: '自定义提供方',
    apiKeyConfigured: 'API 密钥已配置',
    apiKeyMissing: '未配置密钥',
    addProvider: '添加提供方',
    addCustomProvider: '添加自定义提供方',
    providerName: '提供方名称',
    apiKeyLabel: 'API 密钥',
    apiKeyEnvLabel: '环境变量名',
    modelLabel: '模型',
    baseUrlLabel: 'API 地址',
    save: '保存',
    rename: '改展示名',
    saved: '已保存',
    delete: '删除',
    cancel: '取消',
    edit: '编辑',
    keySourceFile: '密钥已保存',
    keySourceEnv: '环境变量',
    keySourceNone: '未设置',
    loading: '加载中…',
    emptyBackends: '暂无后端，点击上方按钮添加提供方',
    invalidCustom: '自定义提供方需要填写 API 地址和至少一个模型',
    customUrlHint: '留空使用官方默认地址',
    addExecutor: '添加执行体',
    addExecutorPair: '家庭执行体（PAIR）',
    addExecutorAgent: '机构执行体（agent）',
    addExecutorPairHint: '把 PAIR 集群（家庭闲置算力）作为上游 Provider 接入',
    addExecutorAgentHint: '把 aipoweredge-agent 节点作为上游 Provider 接入',
    executorScheme: 'scheme：pair://',
    executorSchemeAgent: 'scheme：agent://',
    executorBaseUrlHint: '执行体暴露的 OpenAI 兼容端点（必填，如 http://192.168.1.10:8080/v1）',
    executorKeyHint: '本地执行体通常无需密钥，留空即可',
    executorModelsAuto: '保存后自动探测模型列表并落盘',
    addModel: '添加模型',
    standardModels: '使用标准模型',
    modelPlaceholder: '输入模型名后回车',
    test: '测试',
    testing: '测试中…',
    testOk: '连接成功',
    stateUntested: '未测试',
    fetchModels: '获取模型',
    connectTitle: '接入信息',
    connectSubtitle: '把本网关当作普通 OpenAI 兼容服务，接入任意客户端',
    connEndpoint: 'OpenAI 兼容端口',
    connOpenaiNote: 'POST /v1/chat/completions（对话） · GET /v1/models（模型列表）',
    connConsole: '管理控制台',
    connLanIp: '本机局域网 IP',
    connPort: '端口',
    connSharePort: '共享通道端口（使用者 gateway 接入）',
    connCopy: '复制',
    connCopyModels: '复制模型列表（逗号分隔）',
    connCopied: '已复制',
    connTokenTitle: '访问令牌（使用者 token）',
    connTokenHint: '每台设备用独立机器名换取令牌；面板按机器名计量与管控',
    connModelsTitle: '当前暴露的模型',
    connNoModels: '尚未配置模型 —— 请先在「模型」页添加提供方',
    connCcTitle: '在 cc-switch 中添加此网关',
    connCcName: '名称',
    connCcApiOpenai: 'API 地址（OpenAI / Codex 模板）',
    connCcApiAnthro: 'API 地址（Anthropic / Claude Code 模板）',
    connCcKey: 'API 密钥',
    connCcApiWarn: '不要错误使用：Anthropic / Claude Code 模板必须选第二行地址（不带 /v1）——SDK 会自动追加 /v1/messages，填了带 /v1 的地址会请求 /v1/v1/messages 报 404/405',
    connMemberNote: '终端使用者运行 aipowergateway --role client：UDP 广播免密发现共享者后，经共享通道端口与共享者 gateway 通信；终端工具只需对接本机 gateway',
    connLocalOnly: '仅本机模式：三类入口均只监听 127.0.0.1，局域网使用者无法访问；如需共享请执行 config set bind 0.0.0.0 后重启',
    connAnthroTitle: 'Anthropic 兼容端口（Claude Code）',
    connAnthroEndpoint: '端点：POST /v1/messages（SSE 流式）',
    connAnthroEnv: '环境变量配置（Windows）',
    connAnthroLinux: 'Linux/macOS：set 换成 export 即可',
    connAnthroTokenHint: '令牌来自上方「访问令牌」命令',
    connAnthroUrlNote: '注意：Anthropic 端点填根地址（不带 /v1）——SDK 会自动拼 /v1/messages；带 /v1 会请求 /v1/v1/messages 返回 404/405',
    connTokenReal: '令牌必须是真实内容（非占位符文本）——用上方 curl 换得后粘贴实际 eyJ... 值；永久有效（管理/API 仅监听本机），重开页面不会改变（同机器复用同一 token）',
    connLocalTitle: '本机 key（立即查看）',
    connLocalHint: '无需终端：页面自动显示本机 token（同机器复用，不会因刷新改变；只有点「重新换取」才换新）。机器名保持唯一，计量不中断',
    connLocalMachine: '机器名',
    connLocalBtn: '重新换取',
    connLocalFetch: '换取中…',
    connLocalToken: 'key',
    connLocalExpires: '过期时间',
    connLocalForever: '永久',
    connLocalErr: '换取失败',
    connLocalCopy: '已复制',
    autostartTitle: '开机启动',
    autostartHint: '登录 Windows 时自动启动 AIPowerLink 网关',
    autostartOn: '已开启',
    autostartOff: '已关闭',
    autostartFailed: '操作失败',
    aboutTitle: '关于',
    versionLabel: '版本',
    githubLabel: 'GitHub',
    githubHref: 'https://github.com/aipowerlink/aipowergateway',
    apiKeyRequired: '请先填写 API 密钥',
    modelsFetched: '已获取模型列表',
    fetchModelsFailed: '获取模型失败',
    // 健康轮询（P1）四态状态点与配置
    healthOk: '健康（轮询探测成功）',
    healthDegraded: '降级（连续失败，仍可路由）',
    healthRemoved: '已摘除（连续失败过多，退出路由）',
    healthUntested: '未轮询/待探测',
    healthErrorHint: '最近失败',
    healthFailuresHint: '连续失败次数',
    pollingTitle: '健康轮询',
    pollingHint: '周期探测执行体端点，连续失败自动降级/摘除，恢复后自动回归',
    pollingEnabled: '启用轮询',
    pollingIntervalLabel: '轮询间隔（秒）',
    pollingFailLabel: '降级阈值（连续失败）',
    pollingRemoveLabel: '摘除阈值（连续失败）',
    pollingSaved: '轮询配置已保存',
    // 链路加密（M3）组长端策略
    encTitle: '链路加密',
    encHint: '共享者端策略：aes-gcm = 协商式（缺省，跨网络深链加密）；enforce = 强制（未声明加密的 /v1/* 回 426）；off = 明文',
    encOff: '明文（off）',
    encAesGcm: '协商式（aes-gcm）',
    encEnforce: '强制（enforce）',
    encSaved: '链路加密策略已保存',
    encSavingFail: '保存失败：',
    // 负载红线拦截（挖矿/深伪）
    loadPolicyTitle: '负载红线拦截（挖矿/深伪）',
    loadPolicyHint: '网关侧零知识判定：命中挖矿/深伪请求回 403，不落盘、不过云、不记录内容（合规红线）',
    loadPolicyOn: '已开启',
    loadPolicyOff: '已关闭',
    loadPolicyMining: '挖矿拦截',
    loadPolicyDeepfake: '深伪拦截',
    loadPolicySaved: '负载红线策略已保存',
    loadPolicySavingFail: '操作失败：',
    // 规则执行引擎（模型名=规则名 → 真实上游候选序列）
    rulesTitle: '规则执行引擎（智能路由）',
    rulesHint: '客户端 model 字段填写规则名（如 default-cost），网关按估计 token 数选最省真实模型；上游失败自动回退下一候选',
    rulesLoaded: '已加载规则集',
    rulesCount: '条规则',
    rulesSave: '保存规则集',
    rulesSaved: '规则集已保存，立即生效',
    rulesSaveFail: '保存失败：',
    rulesEditor: '规则集 JSON（model-rule-set.json）',
    rulesEditorHint: '格式：{\"ruleSets\":[{id,name,version,rules:[{match_model,order,strategy,candidates:[{model,max_prompt_tokens}],fallback}]}]}；strategy: token_tier|fixed',
    rulesRuleNames: '可用规则名（model 字段可填）',
    rulesUsageTip: '命中规则的请求响应带 X-APL-Rule / X-APL-Upstream 头；仪表板用量含规则集 token 聚合',
  },
  en: {
    appName: 'AIPowerLink Console',
    navMembers: 'Users',
    navUsage: 'Usage',
    navControls: 'Controls',
    navConnect: 'Connect',
    sharingOn: 'Sharing',
    sharingOff: 'Paused',
    startSharing: 'Start sharing',
    pauseSharing: 'Pause sharing',
    memberList: 'Users',
    memberLocal: 'This machine',
    machineName: 'Machine',
    displayName: 'Display name',
    ip: 'IP',
    status: 'Status',
    online: 'Online',
    offline: 'Offline',
    usage: 'Usage',
    totalTokens: 'Total tokens',
    calls: 'Calls',
    usageTable: 'Usage stats',
    controls: 'Controls',
    kick: 'Ban',
    unban: 'Unban',
    banned: 'Banned',
    gateway: 'Gateway ID',
    details: 'User details',
    joinedAt: 'Joined',
    lastSeen: 'Last seen',
    back: 'Back',
    noSelection: 'Select a user for details',
    refresh: 'Refresh',
    actions: 'Actions',
    exportCsv: 'Export CSV',
    quota: 'Quota',
    unlimited: 'Unlimited',
    models: 'Model breakdown',
    navModels: 'Models',
    modelsTitle: 'Model Settings',
    modelsHint: 'Fill in each provider API key to use its models',
    provider: 'Provider',
    providerCustom: 'Custom provider',
    apiKeyConfigured: 'API key configured',
    apiKeyMissing: 'No API key',
    addProvider: 'Add provider',
    addCustomProvider: 'Add custom provider',
    providerName: 'Provider name',
    apiKeyLabel: 'API key',
    apiKeyEnvLabel: 'Env var name',
    modelLabel: 'Model',
    baseUrlLabel: 'Base URL',
    save: 'Save',
    rename: 'Rename',
    saved: 'Saved',
    delete: 'Delete',
    cancel: 'Cancel',
    edit: 'Edit',
    keySourceFile: 'Key saved',
    keySourceEnv: 'Env var',
    keySourceNone: 'Not set',
    loading: 'Loading…',
    emptyBackends: 'No backends yet. Add a provider above to start.',
    invalidCustom: 'Custom provider requires a base URL and at least one model',
    customUrlHint: 'Leave empty for the official default',
    addExecutor: 'Add executor',
    addExecutorPair: 'Home executor (PAIR)',
    addExecutorAgent: 'Org executor (agent)',
    addExecutorPairHint: 'Use a PAIR cluster (idle home compute) as an upstream provider',
    addExecutorAgentHint: 'Use an aipoweredge-agent node as an upstream provider',
    executorScheme: 'scheme: pair://',
    executorSchemeAgent: 'scheme: agent://',
    executorBaseUrlHint: 'OpenAI-compatible endpoint exposed by the executor (required, e.g. http://192.168.1.10:8080/v1)',
    executorKeyHint: 'Local executors usually need no key — leave empty',
    executorModelsAuto: 'Model list is auto-detected and persisted after saving',
    addModel: 'Add model',
    standardModels: 'Use standard models',
    modelPlaceholder: 'Type a model name, press Enter',
    test: 'Test',
    testing: 'Testing…',
    testOk: 'Connected',
    stateUntested: 'Not tested',
    fetchModels: 'Fetch models',
    connectTitle: 'Connection info',
    connectSubtitle: 'Use this gateway as a plain OpenAI-compatible service from any client',
    connEndpoint: 'OpenAI-compatible port',
    connOpenaiNote: 'POST /v1/chat/completions · GET /v1/models',
    connConsole: 'Admin console',
    connLanIp: 'LAN IP',
    connPort: 'Port',
    connSharePort: 'Gateway channel port (user gateways)',
    connCopy: 'Copy',
    connCopyModels: 'Copy model list (comma-separated)',
    connCopied: 'Copied',
    connTokenTitle: 'Access token (user token)',
    connTokenHint: 'Every device exchanges a token with its own machine name; the panel meters and governs per machine',
    connModelsTitle: 'Exposed models',
    connNoModels: 'No models yet — add a provider on the Models page',
    connCcTitle: 'Add this gateway in cc-switch',
    connCcName: 'Name',
    connCcApiOpenai: 'API address (OpenAI / Codex template)',
    connCcApiAnthro: 'API address (Anthropic / Claude Code template)',
    connCcKey: 'API key',
    connCcApiWarn: 'Do NOT pick the /v1 address for the Anthropic / Claude Code template — the SDK appends /v1/messages itself, so /v1 + /v1/messages = /v1/v1/messages → 404/405. Use the root address instead.',
    connMemberNote: 'Users run aipowergateway --role client: after passwordless UDP discovery, their gateway talks to the sharer gateway over the channel port; local tools only talk to the local gateway',
    connLocalOnly: 'Local-only mode: all three endpoints listen on 127.0.0.1 only; LAN users cannot reach them. Run config set bind 0.0.0.0 and restart to share',
    connAnthroTitle: 'Anthropic-compatible port (Claude Code)',
    connAnthroEndpoint: 'Endpoint: POST /v1/messages (SSE streaming)',
    connAnthroEnv: 'Environment variables (Windows)',
    connAnthroLinux: 'Linux/macOS: replace set with export',
    connAnthroTokenHint: 'Token comes from the user token command above',
    connAnthroUrlNote: 'Note: use the root address (no /v1) — the SDK appends /v1/messages itself; adding /v1 hits /v1/v1/messages (404/405)',
    connTokenReal: 'The token must be the real value (not placeholder text) — paste the actual eyJ... from the curl command above; permanent (management/API listen on localhost only), reused per machine (unchanged on page refresh)',
    connLocalTitle: 'Local key (view now)',
    connLocalHint: 'No terminal needed: the page auto-shows the local token (reused per machine, unchanged on refresh; only "Exchange again" rotates it). Keep the machine name unique so metering stays continuous',
    connLocalMachine: 'Machine name',
    connLocalBtn: 'Exchange again',
    connLocalFetch: 'Exchanging…',
    connLocalToken: 'Key',
    connLocalExpires: 'Expires at',
    connLocalForever: 'Forever',
    connLocalErr: 'Exchange failed',
    connLocalCopy: 'Copied',
    autostartTitle: 'Launch at startup',
    autostartHint: 'Start AIPowerLink gateway automatically when Windows logs in',
    autostartOn: 'Enabled',
    autostartOff: 'Disabled',
    autostartFailed: 'Operation failed',
    aboutTitle: 'About',
    versionLabel: 'Version',
    githubLabel: 'GitHub',
    githubHref: 'https://github.com/aipowerlink/aipowergateway',
    apiKeyRequired: 'API key required',
    modelsFetched: 'Models fetched',
    fetchModelsFailed: 'Failed to fetch models',
    // Health polling (P1) four-state dot and config
    healthOk: 'Healthy (probe ok)',
    healthDegraded: 'Degraded (consecutive failures, still routed)',
    healthRemoved: 'Removed (too many failures, out of routing)',
    healthUntested: 'Not polled / pending probe',
    healthErrorHint: 'Last failure',
    healthFailuresHint: 'Consecutive failures',
    pollingTitle: 'Health polling',
    pollingHint: 'Periodically probes the executor endpoint; auto degrade/remove on consecutive failures, auto recover',
    pollingEnabled: 'Enable polling',
    pollingIntervalLabel: 'Interval (s)',
    pollingFailLabel: 'Degrade threshold (failures)',
    pollingRemoveLabel: 'Remove threshold (failures)',
    pollingSaved: 'Polling config saved',
    // Link encryption (M3) leader-side policy
    encTitle: 'Link encryption',
    encHint: 'Sharer policy: aes-gcm = negotiated (default, encrypted cross-network deep links); enforce = mandatory (unencrypted /v1/* → 426); off = plaintext',
    encOff: 'Plaintext (off)',
    encAesGcm: 'Negotiated (aes-gcm)',
    encEnforce: 'Enforced (enforce)',
    encSaved: 'Link encryption policy saved',
    encSavingFail: 'Failed to save: ',
    // Load whitelist redline (mining / deepfake)
    loadPolicyTitle: 'Load redline block (mining / deepfake)',
    loadPolicyHint: 'Gateway-side zero-knowledge check: mining/deepfake requests get 403; nothing persisted, no cloud upload, no content logging (compliance red line)',
    loadPolicyOn: 'On',
    loadPolicyOff: 'Off',
    loadPolicyMining: 'Mining blocked',
    loadPolicyDeepfake: 'Deepfake blocked',
    loadPolicySaved: 'Load redline policy saved',
    loadPolicySavingFail: 'Operation failed: ',
    rulesTitle: 'Rule engine (smart routing)',
    rulesHint: 'Client fills model with a rule name (e.g. default-cost); gateway picks the cheapest real model that fits the estimated prompt tokens, falls back to next candidate on upstream failure',
    rulesLoaded: 'Loaded rule sets',
    rulesCount: 'rules',
    rulesSave: 'Save rule sets',
    rulesSaved: 'Rule sets saved, active now',
    rulesSaveFail: 'Save failed: ',
    rulesEditor: 'Rule sets JSON (model-rule-set.json)',
    rulesEditorHint: 'Format: {"ruleSets":[{id,name,version,rules:[{match_model,order,strategy,candidates:[{model,max_prompt_tokens}],fallback}]}]}; strategy: token_tier|fixed',
    rulesRuleNames: 'Available rule names (usable as model)',
    rulesUsageTip: 'Rule-matched responses carry X-APL-Rule / X-APL-Upstream headers; usage dashboard aggregates tokens per rule set',
  },
} as const

// 语言上下文（默认英文——全球用户基线，中文可切换）
import { createContext, useContext } from 'react'
export const LangContext = createContext<{ lang: Lang; setLang: (l: Lang) => void }>({ lang: 'en', setLang: () => {} })
export function useLang() { return useContext(LangContext) }
export function useT() { const { lang } = useLang(); return L[lang] }

export type Lang = keyof typeof L
export type Dict = typeof L['zh']